theme = "catppuccin_mocha"

[editor]
cursorline = true
color-modes = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner", "file-name", "diagnostics"]
right = ["file-type", "file-encoding", "selections", "position"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true